name: Smoke test (pinging the website).
on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:
jobs:
  verify-website-returns-html:
    runs-on: ubuntu-latest
    steps:
      # Uses https://github.com/marketplace/actions/curl-axiosjs
      - name: "Call API"
        uses: indiesdev/curl@v1.1
        with:
          url: https://sustainability.equinor.com/
          method: "GET"
          accept: 200
          # headers: '{ "custom-header": "value" }'
          timeout: 3000
          log-response: true
