name: Smoke test (pinging the website).
on:
  schedule:
    - cron: "55 * * * *"
  workflow_dispatch:
jobs:
  verify-website-returns-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # Uses https://github.com/marketplace/actions/curl-axiosjs
      - name: "Fetch website"
        id: website
        uses: indiesdev/curl@v1.1
        with:
          url: https://sustainability.equinor.com/
          method: "GET"
          accept: 200
          timeout: 3000
          log-response: true
      - run: |
          # Verify that response contains '<!doctype html>'
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/check-response.sh";
          SMOKE_TEST_RESPONSE=${{ steps.website.outputs.response }} ${GITHUB_WORKSPACE}/.github/workflows/check-response.sh
